### ISSUE TITLE
Log error traces

### ISSUE THREAD

**Issue by Koc** [tony2001/pinba_extension#22]
It would be nice track error traces in prod.

**Comment by Sannis** [comment]
You can simply writhe them to PHP error logs using custom error handler.

**Comment by Koc** [comment]
It would be useful attach error trace to pinba profile. And also there are no possibility to trace fatal errors on production: currently only xdebug allows retrieve stacktrace for fatal errors but install it on live server is bad idea for performance reason.

**Comment by Koc** [comment]
I think that it is possible to integrate https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Debug/Resources/ext into pinba extension. If we are using pinba not only for performance but also for and errors monitoring - would be better track fatal error with traces.

**Comment by muxx** [comment]
You can get error traces on PHP7 where errors are the exceptions. And traces extremely increase protocol format and pinba tables size.

**Comment by Koc** [comment]
Indeed, this ussne no more actual since php 7.
