### ISSUE TITLE
apache2 gracefull restart problem

### ISSUE THREAD

**Issue by if22** [tony2001/pinba_extension#26]
Hey,
I get that error every time I'm trying to do "service apache2 reload" on my Ubuntu 14.04 server. And Apache stops working. 

[Thu Dec 24 00:13:39.016451 2015] [mpm_prefork:notice] [pid 8721] AH00171: Graceful restart requested, doing restart
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: pinba.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:954] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
[Thu Dec 24 00:13:42.926783 2015] [core:notice] [pid 8721] AH00060: seg fault or similar nasty error detected in the parent process

After "server apache2 restart" server goes online.
Could you please help how to fix that error?
P.S. Ubuntu 14.04.3, Apache-ITK 2.4, PHP 5.5 and pinba extension were installed from official repo.

Thanks!

**Comment by tony2001** [comment]
I don't have any official repo, so I guess it's something not really official.
Looking at the error message, it's also outdated - I've dropped libprotobuf somewhere in 2012..

**Comment by if22** [comment]
I mean official Canonical repositories.  ...and it is v1.0.0 in it. I thought, that I installed v. 1.1.0. Will try to install from source.
Sorry.
