### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by huoding** [tony2001/pinba_extension#29]
# php -v
PHP 5.5.24 (cli) (built: Apr 18 2015 00:24:15)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with blackfire v1.10.6, https://blackfire.io, by Blackfireio Inc.

# make install
/bin/sh /home/foo/pinba_extension/libtool --mode=compile cc -DNDEBUG -I. -I/home/foo/pinba_extension -DPHP_ATOM_INC -I/home/foo/pinba_extension/include -I/home/foo/pinba_extension/main -I/home/foo/pinba_extension -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/foo/pinba_extension/pinba.c -o pinba.lo
libtool: compile:  cc -DNDEBUG -I. -I/home/foo/pinba_extension -DPHP_ATOM_INC -I/home/foo/pinba_extension/include -I/home/foo/pinba_extension/main -I/home/foo/pinba_extension -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/foo/pinba_extension/pinba.c  -fPIC -DPIC -o .libs/pinba.o
/home/foo/pinba_extension/pinba.c: In function 'php_timer_hash_dtor':
/home/foo/pinba_extension/pinba.c:319: warning: initialization makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c: In function 'php_tag_hash_dtor':
/home/foo/pinba_extension/pinba.c:330: warning: initialization makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c: At top level:
/home/foo/pinba_extension/pinba.c:381: error: expected ')' before '*' token
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_timer_stop_helper':
/home/foo/pinba_extension/pinba.c:407: warning: cast to pointer from integer of different size
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_dict_find_or_add':
/home/foo/pinba_extension/pinba.c:509: warning: comparison between pointer and integer
/home/foo/pinba_extension/pinba.c: In function '_pinba_fetch_global_var':
/home/foo/pinba_extension/pinba.c:523: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:524: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:524: error: request for member 'value' in something not a structure or union
/home/foo/pinba_extension/pinba.c:524: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:524: error: request for member 'value' in something not a structure or union
/home/foo/pinba_extension/pinba.c: In function 'php_create_pinba_packet':
/home/foo/pinba_extension/pinba.c:677: warning: passing argument 2 of 'zend_hash_sort' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:220: note: expected 'sort_func_t' but argument is of type 'int (*)(const void *, const void *)'
/home/foo/pinba_extension/pinba.c:677: error: too few arguments to function 'zend_hash_sort'
/home/foo/pinba_extension/pinba.c:683: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:685: error: 'zend_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:685: error: (Each undeclared identifier is reported only once
/home/foo/pinba_extension/pinba.c:685: error: for each function it appears in.)
/home/foo/pinba_extension/pinba.c:685: error: 'key' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:696: warning: passing argument 3 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'uint *' but argument is of type 'zend_ulong *'
/home/foo/pinba_extension/pinba.c:696: warning: passing argument 4 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'ulong *' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:696: error: too few arguments to function 'zend_hash_get_current_key_ex'
/home/foo/pinba_extension/pinba.c:718: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:730: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:742: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:772: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:182: note: expected 'void **' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:772: error: too few arguments to function 'zend_hash_get_current_data_ex'
/home/foo/pinba_extension/pinba.c:774: error: 'str' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:777: warning: passing argument 3 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'uint *' but argument is of type 'zend_ulong *'
/home/foo/pinba_extension/pinba.c:777: warning: passing argument 4 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'ulong *' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:777: error: too few arguments to function 'zend_hash_get_current_key_ex'
/home/foo/pinba_extension/pinba.c:822: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_key_compare':
/home/foo/pinba_extension/pinba.c:995: error: 'Bucket' has no member named 'key'
/home/foo/pinba_extension/pinba.c:998: error: 'Bucket' has no member named 'key'
/home/foo/pinba_extension/pinba.c:1001: error: 'Bucket' has no member named 'key'
/home/foo/pinba_extension/pinba.c:1004: error: 'Bucket' has no member named 'key'
/home/foo/pinba_extension/pinba.c:1007: error: too few arguments to function 'string_compare_function'
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_array_to_tags':
/home/foo/pinba_extension/pinba.c:1015: error: 'zend_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1015: error: 'tag_name_str' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1023: warning: passing argument 2 of 'zend_hash_sort' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:220: note: expected 'sort_func_t' but argument is of type 'int (*)(const void *, const void *)'
/home/foo/pinba_extension/pinba.c:1023: error: too few arguments to function 'zend_hash_sort'
/home/foo/pinba_extension/pinba.c:1026: error: expected ';' before '{' token
/home/foo/pinba_extension/pinba.c:1103:65: error: macro "add_assoc_stringl" requires 5 arguments, but only 4 given
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_get_timer_info':
/home/foo/pinba_extension/pinba.c:1103: error: 'add_assoc_stringl' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1110: warning: passing argument 1 of 'zval_add_ref' from incompatible pointer type
/usr/include/php/Zend/zend_variables.h:78: note: expected 'struct zval **' but argument is of type 'struct zval *'
/home/foo/pinba_extension/pinba.c: In function 'pinba_client_new':
/home/foo/pinba_extension/pinba.c:1171: error: 'zend_object' has no member named 'handlers'
/home/foo/pinba_extension/pinba.c:1173: warning: passing argument 4 of '_zend_hash_init' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:100: note: expected 'dtor_func_t' but argument is of type 'void (*)(struct zval *)'
/home/foo/pinba_extension/pinba.c:1174: warning: passing argument 4 of '_zend_hash_init' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:100: note: expected 'dtor_func_t' but argument is of type 'void (*)(struct zval *)'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_start':
/home/foo/pinba_extension/pinba.c:1192: error: 'zend_resource' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1192: error: 'rsrc' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1228: warning: passing argument 1 of 'zend_register_resource' from incompatible pointer type
/usr/include/php/Zend/zend_list.h:82: note: expected 'struct zval *' but argument is of type 'struct pinba_timer_t *'
/home/foo/pinba_extension/pinba.c:1228: warning: passing argument 2 of 'zend_register_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:82: note: expected 'void *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1228: error: too few arguments to function 'zend_register_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_add':
/home/foo/pinba_extension/pinba.c:1252: error: 'zend_resource' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1252: error: 'rsrc' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1291: warning: passing argument 1 of 'zend_register_resource' from incompatible pointer type
/usr/include/php/Zend/zend_list.h:82: note: expected 'struct zval *' but argument is of type 'struct pinba_timer_t *'
/home/foo/pinba_extension/pinba.c:1291: warning: passing argument 2 of 'zend_register_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:82: note: expected 'void *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1291: error: too few arguments to function 'zend_register_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_stop':
/home/foo/pinba_extension/pinba.c:1316: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1316: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1316: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1316: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_delete':
/home/foo/pinba_extension/pinba.c:1339: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1339: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1339: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1339: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_data_merge':
/home/foo/pinba_extension/pinba.c:1367: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1367: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1367: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1367: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c:1372:74: error: macro "zend_hash_merge" requires 6 arguments, but only 4 given
/home/foo/pinba_extension/pinba.c:1372: error: 'zend_hash_merge' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_data_replace':
/home/foo/pinba_extension/pinba.c:1395: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1395: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1395: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1395: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c:1400: warning: passing argument 1 of '_zval_ptr_dtor' from incompatible pointer type
/usr/include/php/Zend/zend_variables.h:51: note: expected 'struct zval **' but argument is of type 'struct zval *'
/home/foo/pinba_extension/pinba.c:1405: warning: passing argument 1 of '_zval_ptr_dtor' from incompatible pointer type
/usr/include/php/Zend/zend_variables.h:51: note: expected 'struct zval **' but argument is of type 'struct zval *'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_tags_merge':
/home/foo/pinba_extension/pinba.c:1433: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1433: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1433: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1433: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_tags_replace':
/home/foo/pinba_extension/pinba.c:1498: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1498: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1498: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1498: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c:1587:59: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_get_info':
/home/foo/pinba_extension/pinba.c:1587: error: 'add_assoc_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1589:61: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1593:69: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1595:66: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1599:69: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1601:66: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1604:63: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/home/foo/pinba_extension/pinba.c:1609: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:182: note: expected 'void **' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1609: error: too few arguments to function 'zend_hash_get_current_data_ex'
/home/foo/pinba_extension/pinba.c:1611: error: 'zend_resource' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1611: error: 'rsrc' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1628: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:182: note: expected 'void **' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1628: error: too few arguments to function 'zend_hash_get_current_data_ex'
/home/foo/pinba_extension/pinba.c:1630: error: 'zend_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1630: error: 'key' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1632: warning: initialization makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:1634: warning: passing argument 3 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'uint *' but argument is of type 'zend_ulong *'
/home/foo/pinba_extension/pinba.c:1634: warning: passing argument 4 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'ulong *' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1634: error: too few arguments to function 'zend_hash_get_current_key_ex'
/home/foo/pinba_extension/pinba.c:1635: error: too few arguments to function 'add_assoc_string_ex'
/home/foo/pinba_extension/pinba.c:1663:31: error: macro "RETVAL_STRINGL" requires 3 arguments, but only 2 given
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_get_data':
/home/foo/pinba_extension/pinba.c:1663: error: 'RETVAL_STRINGL' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timer_get_info':
/home/foo/pinba_extension/pinba.c:1680: warning: passing argument 1 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'struct zval **' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1680: warning: passing argument 2 of 'zend_fetch_resource' makes integer from pointer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'int' but argument is of type 'char *'
/home/foo/pinba_extension/pinba.c:1680: warning: passing argument 3 of 'zend_fetch_resource' makes pointer from integer without a cast
/usr/include/php/Zend/zend_list.h:83: note: expected 'const char *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1680: error: too few arguments to function 'zend_fetch_resource'
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timers_stop':
/home/foo/pinba_extension/pinba.c:1699: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:182: note: expected 'void **' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1699: error: too few arguments to function 'zend_hash_get_current_data_ex'
/home/foo/pinba_extension/pinba.c:1701: error: 'zend_resource' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1701: error: 'rsrc' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_timers_get':
/home/foo/pinba_extension/pinba.c:1727: warning: passing argument 2 of 'zend_hash_get_current_data_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:182: note: expected 'void **' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1727: error: too few arguments to function 'zend_hash_get_current_data_ex'
/home/foo/pinba_extension/pinba.c:1729: error: 'zend_resource' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1729: error: 'rsrc' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_tag_get':
/home/foo/pinba_extension/pinba.c:1884: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:1888:21: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
/home/foo/pinba_extension/pinba.c:1888: error: 'RETURN_STRING' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zif_pinba_tags_get':
/home/foo/pinba_extension/pinba.c:1923: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:1925: error: 'zend_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1925: error: 'key' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1928: warning: passing argument 3 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'uint *' but argument is of type 'zend_ulong *'
/home/foo/pinba_extension/pinba.c:1928: warning: passing argument 4 of 'zend_hash_get_current_key_ex' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:179: note: expected 'ulong *' but argument is of type 'struct Bucket **'
/home/foo/pinba_extension/pinba.c:1928: error: too few arguments to function 'zend_hash_get_current_key_ex'
/home/foo/pinba_extension/pinba.c:1929: error: too few arguments to function 'add_assoc_string_ex'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient___construct':
/home/foo/pinba_extension/pinba.c:1951: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:1955:45: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
/home/foo/pinba_extension/pinba.c:1955: error: 'zend_hash_get_current_data' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1958: error: 'zend_string' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:1958: error: 'str' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setHostname':
/home/foo/pinba_extension/pinba.c:2001: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setServername':
/home/foo/pinba_extension/pinba.c:2002: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setScriptname':
/home/foo/pinba_extension/pinba.c:2003: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setSchema':
/home/foo/pinba_extension/pinba.c:2004: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setRequestCount':
/home/foo/pinba_extension/pinba.c:2025: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setMemoryFootprint':
/home/foo/pinba_extension/pinba.c:2026: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setMemoryPeak':
/home/foo/pinba_extension/pinba.c:2027: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setDocumentSize':
/home/foo/pinba_extension/pinba.c:2028: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setStatus':
/home/foo/pinba_extension/pinba.c:2029: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setRequestTime':
/home/foo/pinba_extension/pinba.c:2030: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setRusage':
/home/foo/pinba_extension/pinba.c:2044: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:2052:45: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
/home/foo/pinba_extension/pinba.c:2052: error: 'zend_hash_get_current_data' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_setTag':
/home/foo/pinba_extension/pinba.c:2072: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'php_pinba_client_timer_add_set':
/home/foo/pinba_extension/pinba.c:2096: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:2121:46: error: macro "zend_hash_get_current_data" requires 2 arguments, but only 1 given
/home/foo/pinba_extension/pinba.c:2121: error: 'zend_hash_get_current_data' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:2153: warning: assignment makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_send':
/home/foo/pinba_extension/pinba.c:2202: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c: In function 'zim_PinbaClient_getData':
/home/foo/pinba_extension/pinba.c:2239: warning: passing argument 1 of 'php_pinba_client_object' makes pointer from integer without a cast
/home/foo/pinba_extension/pinba.c:135: note: expected 'struct zend_object *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:2247:31: error: macro "RETVAL_STRINGL" requires 3 arguments, but only 2 given
/home/foo/pinba_extension/pinba.c:2247: error: 'RETVAL_STRINGL' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c: In function 'OnUpdateCollectorAddress':
/home/foo/pinba_extension/pinba.c:2455: error: request for member 'val' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2455: error: request for member 'len' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2482: warning: passing argument 3 of 'OnUpdateString' makes integer from pointer without a cast
/usr/include/php/Zend/zend_ini.h:180: note: expected 'uint' but argument is of type 'void *'
/home/foo/pinba_extension/pinba.c:2482: warning: passing argument 6 of 'OnUpdateString' makes pointer from integer without a cast
/usr/include/php/Zend/zend_ini.h:180: note: expected 'void *' but argument is of type 'int'
/home/foo/pinba_extension/pinba.c:2482: error: too few arguments to function 'OnUpdateString'
/home/foo/pinba_extension/pinba.c: In function 'zm_startup_pinba':
/home/foo/pinba_extension/pinba.c:2516: error: 'php_timer_resource_dtor' undeclared (first use in this function)
/home/foo/pinba_extension/pinba.c:2525: warning: assignment from incompatible pointer type
/home/foo/pinba_extension/pinba.c:2526: warning: assignment from incompatible pointer type
/home/foo/pinba_extension/pinba.c:2530: error: too few arguments to function 'zend_register_internal_class_ex'
/home/foo/pinba_extension/pinba.c:2531: warning: assignment from incompatible pointer type
/home/foo/pinba_extension/pinba.c:2534: error: 'zend_object_handlers' has no member named 'dtor_obj'
/home/foo/pinba_extension/pinba.c:2535: error: 'zend_object_handlers' has no member named 'free_obj'
/home/foo/pinba_extension/pinba.c:2537: error: 'zend_object_handlers' has no member named 'offset'
/home/foo/pinba_extension/pinba.c: In function 'zm_activate_pinba':
/home/foo/pinba_extension/pinba.c:2579: warning: passing argument 4 of '_zend_hash_init' from incompatible pointer type
/usr/include/php/Zend/zend_hash.h:100: note: expected 'dtor_func_t' but argument is of type 'void (*)(struct zval *)'
/home/foo/pinba_extension/pinba.c:2591: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2591: error: request for member 'value' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2591: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2591: error: request for member 'value' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2596: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2596: error: request for member 'value' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2596: error: request for member 'type' in something not a structure or union
/home/foo/pinba_extension/pinba.c:2596: error: request for member 'value' in something not a structure or union
make: *** [pinba.lo] Error 1

**Comment by tony2001** [comment]
You can find PHP5 version of the code in php5 branch.
Master now contains PHP7 version.
